### PR TITLE
Fixing 500 response errors

### PR DESCRIPTION
**Pull request by Ankur-Agrawal-ece20**
@krashish8 please review so that we can merge.
1) Fixing 500 error responses
2) Changed response for already registered users of a college.

### CODE REVIEW

**Review by krashish8 — CHANGES_REQUESTED** [review]
The syntax is wrong... please refer to the documentation.
It's a method in `django.shortcuts` and needs to be imported

**Comment by Ankur-Agrawal-ece20** [comment]
> The syntax is wrong... please refer to the documentation. It's a method in `django.shortcuts` and needs to be imported

**Sorry for the mistake.**
Please review now!

**Comment by krashish8** [comment]
@Ankur-Agrawal-ece20  Just one last suggestion before merging: In the Team Create view and serializer, the game field is supposed to contain an underscore for splitting. But if the underscore is omitted, it returns a 500 Error. It should throw either BadRequest or NotFound error.

**Comment by Ankur-Agrawal-ece20** [comment]
> @Ankur-Agrawal-ece20 Just one last suggestion before merging: In the Team Create view and serializer, the game field is supposed to contain an underscore for splitting. But if the underscore is omitted, it returns a 500 Error. It should throw either BadRequest or NotFound error.

Please tell me if any other changes are required.

**Review by krashish8 — APPROVED** [review]
Great work! Merging. 🥳

**Comment by krashish8** [comment]
> Please tell me if any other changes are required.

Well, enough for now 😅

Just a suggestion for the future - when using try-except block, you should catch only particular errors and not "all" the errors. And obviously use it only for those statements that are impacted, not the complete block of code.

It helps avoiding the cases when due to some other unexpected errors, the flow of control goes to the `except` block. Also, when giving back a 400 Response, it's good to include some "helper" message.

No worries for now, but this might be helpful in the future.

**Pull request merged**
